[package]
name = "beholder-adapters-mnestic"
version.workspace = true
edition.workspace = true

[features]
default = []
devtools = ["sqlite"]
parallel = ["mnestic-engine/rayon"]
sqlite = ["dep:sqlite", "mnestic-engine/storage-sqlite", "mnestic-engine/storage-sqlite-src"]

[dependencies]
beholder-domain.workspace = true
beholder-dto.workspace = true
mnestic-engine = { package = "mnestic", version = "0.14.0", default-features = false }
sqlite = { version = "0.36.0", optional = true }
