[package]
name = "beholder-adapters-mnestic"
version.workspace = true
edition.workspace = true

[features]
default = []
parallel = ["mnestic-engine/rayon"]
sqlite = ["mnestic-engine/storage-sqlite", "mnestic-engine/storage-sqlite-src"]

[dependencies]
beholder-domain.workspace = true
beholder-dto.workspace = true
mnestic-engine = { package = "mnestic", version = "0.14.0", default-features = false }
