[workspace]
resolver = "3"
default-members = ["crates/cli"]
members = [
    "crates/cli",
    "crates/daemon",
    "crates/daemon-client",
    "crates/protocol",
    "crates/presentation",
    "crates/shell-mnestic",
    "crates/adapters-mnestic",
    "crates/adapters-protobuf",
    "crates/adapters-git",
    "crates/adapters-treesitter-elixir",
    "crates/adapters-treesitter-rust",
    "crates/adapters-treesitter-typescript",
    "crates/domain",
    "crates/dto",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
beholder-adapters-mnestic = { path = "crates/adapters-mnestic", default-features = false }
beholder-adapters-git = { path = "crates/adapters-git" }
beholder-adapters-protobuf = { path = "crates/adapters-protobuf" }
beholder-adapters-treesitter-elixir = { path = "crates/adapters-treesitter-elixir" }
beholder-adapters-treesitter-rust = { path = "crates/adapters-treesitter-rust" }
beholder-adapters-treesitter-typescript = { path = "crates/adapters-treesitter-typescript" }
beholder-domain = { path = "crates/domain" }
beholder-dto = { path = "crates/dto" }
beholder-daemon-client = { path = "crates/daemon-client" }
beholder-protocol = { path = "crates/protocol" }
rayon = "1.10.0"
serde = { version = "1.0.228", features = ["derive"] }
