// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: beholder/worker/v1/worker.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyzerWorker_Analyze_FullMethodName = "/beholder.worker.v1.AnalyzerWorker/Analyze"
)

// AnalyzerWorkerClient is the client API for AnalyzerWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyzerWorkerClient interface {
	Analyze(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AnalyzeRequest, AnalyzeEvent], error)
}

type analyzerWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzerWorkerClient(cc grpc.ClientConnInterface) AnalyzerWorkerClient {
	return &analyzerWorkerClient{cc}
}

func (c *analyzerWorkerClient) Analyze(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AnalyzeRequest, AnalyzeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyzerWorker_ServiceDesc.Streams[0], AnalyzerWorker_Analyze_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeRequest, AnalyzeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyzerWorker_AnalyzeClient = grpc.BidiStreamingClient[AnalyzeRequest, AnalyzeEvent]

// AnalyzerWorkerServer is the server API for AnalyzerWorker service.
// All implementations must embed UnimplementedAnalyzerWorkerServer
// for forward compatibility.
type AnalyzerWorkerServer interface {
	Analyze(grpc.BidiStreamingServer[AnalyzeRequest, AnalyzeEvent]) error
	mustEmbedUnimplementedAnalyzerWorkerServer()
}

// UnimplementedAnalyzerWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyzerWorkerServer struct{}

func (UnimplementedAnalyzerWorkerServer) Analyze(grpc.BidiStreamingServer[AnalyzeRequest, AnalyzeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedAnalyzerWorkerServer) mustEmbedUnimplementedAnalyzerWorkerServer() {}
func (UnimplementedAnalyzerWorkerServer) testEmbeddedByValue()                        {}

// UnsafeAnalyzerWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzerWorkerServer will
// result in compilation errors.
type UnsafeAnalyzerWorkerServer interface {
	mustEmbedUnimplementedAnalyzerWorkerServer()
}

func RegisterAnalyzerWorkerServer(s grpc.ServiceRegistrar, srv AnalyzerWorkerServer) {
	// If the following call pancis, it indicates UnimplementedAnalyzerWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyzerWorker_ServiceDesc, srv)
}

func _AnalyzerWorker_Analyze_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyzerWorkerServer).Analyze(&grpc.GenericServerStream[AnalyzeRequest, AnalyzeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyzerWorker_AnalyzeServer = grpc.BidiStreamingServer[AnalyzeRequest, AnalyzeEvent]

// AnalyzerWorker_ServiceDesc is the grpc.ServiceDesc for AnalyzerWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyzerWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beholder.worker.v1.AnalyzerWorker",
	HandlerType: (*AnalyzerWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Analyze",
			Handler:       _AnalyzerWorker_Analyze_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "beholder/worker/v1/worker.proto",
}

const (
	AnalyzerPlugin_Describe_FullMethodName = "/beholder.worker.v1.AnalyzerPlugin/Describe"
)

// AnalyzerPluginClient is the client API for AnalyzerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyzerPluginClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
}

type analyzerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzerPluginClient(cc grpc.ClientConnInterface) AnalyzerPluginClient {
	return &analyzerPluginClient{cc}
}

func (c *analyzerPluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, AnalyzerPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzerPluginServer is the server API for AnalyzerPlugin service.
// All implementations must embed UnimplementedAnalyzerPluginServer
// for forward compatibility.
type AnalyzerPluginServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	mustEmbedUnimplementedAnalyzerPluginServer()
}

// UnimplementedAnalyzerPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyzerPluginServer struct{}

func (UnimplementedAnalyzerPluginServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedAnalyzerPluginServer) mustEmbedUnimplementedAnalyzerPluginServer() {}
func (UnimplementedAnalyzerPluginServer) testEmbeddedByValue()                        {}

// UnsafeAnalyzerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzerPluginServer will
// result in compilation errors.
type UnsafeAnalyzerPluginServer interface {
	mustEmbedUnimplementedAnalyzerPluginServer()
}

func RegisterAnalyzerPluginServer(s grpc.ServiceRegistrar, srv AnalyzerPluginServer) {
	// If the following call pancis, it indicates UnimplementedAnalyzerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyzerPlugin_ServiceDesc, srv)
}

func _AnalyzerPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerPluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyzerPlugin_ServiceDesc is the grpc.ServiceDesc for AnalyzerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyzerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beholder.worker.v1.AnalyzerPlugin",
	HandlerType: (*AnalyzerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _AnalyzerPlugin_Describe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beholder/worker/v1/worker.proto",
}
