[package]
name = "beholder-adapters-treesitter-rust"
version.workspace = true
edition.workspace = true

[dependencies]
beholder-adapters-treesitter.workspace = true
beholder-domain.workspace = true
beholder-indexing.workspace = true
rayon.workspace = true
ra_ap_syntax = "0.0.348"
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
tree-sitter = "0.26.12"
tree-sitter-rust = "0.24.2"
toml.workspace = true
