[package]
name = "beholder-graph-ui"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
beholder-dto.workspace = true
beholder-daemon-client.workspace = true
beholder-domain.workspace = true
beholder-observability.workspace = true
serde.workspace = true
tauri = { version = "2", features = [] }
tracing = "0.1.44"
