fileGroups:
  sources:
    - 'Cargo.toml'
    - 'src/**/*.rs'

tasks:
  check:
    command: 'cargo check'
    inputs:
      - '@group(sources)'
      - '/Cargo.lock'
      - '/Cargo.toml'

  test:
    command: 'cargo test'
    inputs:
      - '@group(sources)'
      - '/Cargo.lock'
      - '/Cargo.toml'

  smoke:
    command: 'cargo test workspace_smoke'
    deps:
      - '^:smoke'
    inputs:
      - '@group(sources)'
      - '/Cargo.lock'
      - '/Cargo.toml'

  lint:
    command: 'cargo clippy --all-targets -- -D warnings'
    inputs:
      - '@group(sources)'
      - '/Cargo.lock'
      - '/Cargo.toml'

  format:
    command: 'cargo fmt -- --check'
    inputs:
      - '@group(sources)'
      - '/Cargo.toml'
