use super::{
    grpc::{GeneratedGrpcMethod, literal, module_id},
    model::{DefinitionKind, TypescriptAnalysis},
};
use beholder_domain::{
    Confidence, DependencyRelation, GrpcBindingCandidate, GrpcBindingRole, Observation, Provenance,
    RpcCardinality, SemanticRelation,
};
use std::{collections::BTreeMap, path::Path};

pub(super) fn is_generated_source(path: &Path, source: &str) -> bool {
    path.file_stem()
        .and_then(|name| name.to_str())
        .is_some_and(|name| name.ends_with(".generated") || name.ends_with(".gen"))
        || source.lines().take(20).any(|line| {
            let line = line.to_ascii_lowercase();
            line.contains("@generated")
                || line.contains("generated by")
                || line.contains("do not edit")
        })
}

pub(super) fn grpc_methods<'a>(
    repository: &str,
    sources: &[(&'a Path, &TypescriptAnalysis)],
) -> Vec<GeneratedGrpcMethod<'a>> {
    let mut methods = Vec::new();
    for (path, analysis) in sources {
        let constants = analysis
            .string_constants
            .iter()
            .filter_map(|constant| literal(&constant.value).map(|value| (&constant.name, value)))
            .collect::<BTreeMap<_, _>>();
        let module = module_id(repository, path, analysis);
        for definition in &analysis.definitions {
            let Some((class, source_method)) = definition.qualified_name.rsplit_once('/') else {
                continue;
            };
            let Some(service_name) = class.strip_suffix("ClientImpl") else {
                continue;
            };
            let Some(service) = constants.get(&format!("{service_name}ServiceName")) else {
                continue;
            };
            for call in &definition.calls {
                if call.receiver.as_deref() != Some("this.rpc") || call.name != "request" {
                    continue;
                }
                let Some(method) = call.arguments.get(1).and_then(|value| literal(value)) else {
                    continue;
                };
                methods.push(GeneratedGrpcMethod {
                    short_service: service_name.into(),
                    service: service.to_string(),
                    method: method.into(),
                    source_method: source_method.into(),
                    local_symbol: format!("{module}/{}", definition.qualified_name),
                    path,
                    line: call.line,
                });
            }
        }
        let Some(package) = analysis
            .string_constants
            .iter()
            .find(|constant| constant.name == "protobufPackage")
            .and_then(|constant| literal(&constant.value))
        else {
            continue;
        };
        for definition in &analysis.definitions {
            let Some((client, source_method)) = definition.qualified_name.rsplit_once('/') else {
                continue;
            };
            let Some(service_name) = client.strip_suffix("Client") else {
                continue;
            };
            let mut method = source_method.to_owned();
            if let Some(first) = method.get_mut(..1) {
                first.make_ascii_uppercase();
            }
            methods.push(GeneratedGrpcMethod {
                short_service: service_name.into(),
                service: format!("{package}.{service_name}"),
                method,
                source_method: source_method.into(),
                local_symbol: format!("{module}/{}", definition.qualified_name),
                path,
                line: definition.line,
            });
        }
    }
    methods
}

pub(super) fn client_bindings(
    generated: &[GeneratedGrpcMethod<'_>],
    observations: &[Observation],
) -> Vec<GrpcBindingCandidate> {
    generated
        .iter()
        .filter(|generated| {
            observations.iter().any(|observation| {
                observation.relation == SemanticRelation::Dependency(DependencyRelation::Calls)
                    && observation.to.as_str() == generated.local_symbol
                    && observation.from.as_str() != generated.local_symbol
            })
        })
        .map(|generated| GrpcBindingCandidate {
            local_symbol: generated.local_symbol.as_str().into(),
            role: GrpcBindingRole::Client,
            service: generated.service.clone(),
            method: generated.method.clone(),
            cardinality: RpcCardinality::Unary,
            evidence: format!("{}:{}", generated.path.display(), generated.line).into(),
            confidence: Confidence::Exact,
            provenance: Provenance::Generated,
        })
        .collect()
}

pub(super) fn message_observations(
    repository: &str,
    analysis: &TypescriptAnalysis,
    path: &Path,
) -> Vec<Observation> {
    if !analysis.generated {
        return Vec::new();
    }
    let Some(package) = analysis
        .string_constants
        .iter()
        .find(|constant| constant.name == "protobufPackage")
        .and_then(|constant| literal(&constant.value))
    else {
        return Vec::new();
    };
    let module = module_id(repository, path, analysis);
    let mut definitions = BTreeMap::new();
    for definition in &analysis.definitions {
        if definition.kind == DefinitionKind::Namespace
            && !definition.qualified_name.contains('/')
            && !definition.qualified_name.contains('_')
        {
            *definitions.entry(&definition.qualified_name).or_insert(0) += 1;
        }
    }
    definitions
        .into_iter()
        .filter(|(_, occurrences)| *occurrences > 1)
        .map(|(name, _)| Observation {
            from: format!("{module}/{name}").into(),
            relation: SemanticRelation::Dependency(DependencyRelation::BindsContract),
            to: format!("proto-type://{package}.{name}").into(),
            evidence: path.display().to_string().into(),
            confidence: Confidence::Exact,
            provenance: Provenance::Generated,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        SourceLanguage, analysis::analyze_with_plugins, analyze, plugin::built_in_plugins,
    };

    #[test]
    fn binds_only_used_ts_proto_clients() {
        let analysis = analyze(
            r#"
            export const RPCServiceServiceName = "example.checkout.v1.RPCService";
            export class RPCServiceClientImpl {
              initializeOrder(request: Request) {
                return this.rpc.request(this.service, "InitializeOrder", request);
              }
            }
            "#,
            SourceLanguage::TypeScript,
        )
        .unwrap();
        let methods = grpc_methods(
            "example",
            &[(Path::new("generated/checkout.ts"), &analysis)],
        );
        assert!(client_bindings(&methods, &[]).is_empty());

        let client =
            "repo://example/typescript/generated/checkout/RPCServiceClientImpl/initializeOrder";
        let observations = vec![Observation::dependency(
            "repo://example/typescript/src/caller/run",
            DependencyRelation::Calls,
            client,
            "src/caller.ts:2",
        )];
        let bindings = client_bindings(&methods, &observations);
        assert!(bindings.iter().any(|binding| {
            binding.local_symbol.as_str() == client
                && binding.service == "example.checkout.v1.RPCService"
                && binding.method == "InitializeOrder"
        }));
    }

    #[test]
    fn binds_generated_messages_to_canonical_types() {
        let source = r#"
            export const protobufPackage = "example.checkout.v1";
            export interface InitializeOrderRequest { id: string }
            export const InitializeOrderRequest = {
              encode(message: InitializeOrderRequest) { return message; },
              decode(input: Uint8Array) { return input; },
            };
        "#;
        let path = Path::new("generated/initialize_order.generated.ts");
        let analysis = analyze_with_plugins(
            source,
            SourceLanguage::TypeScript,
            path,
            &built_in_plugins().unwrap(),
        )
        .unwrap();

        let observations = message_observations("example", &analysis, path);

        assert!(observations.iter().any(|observation| {
            observation.from.as_str()
                == "repo://example/typescript/generated/initialize_order.generated/InitializeOrderRequest"
                && observation.to.as_str()
                    == "proto-type://example.checkout.v1.InitializeOrderRequest"
        }));
    }
}
